### ISSUE TITLE
API help

### ISSUE THREAD

**Issue by Nsadow311** [Allvaa/nekobot-api#28]
The API does not sends images... I am using JS

**Comment by Allvaa** [comment]
um. what error?

**Comment by Nsadow311** [comment]
I dont get anything from the API, I do nekobot.xyz/api/image?coffee plop it into my code where the URL would go and I dont get anything at all...  There is not error that is stated in the console, all I get is a message from my bot saying "Ummm something is not right try again later" if the status code does not equal 200

**Comment by Allvaa** [comment]
well you missed the **type** param. try `nekobot.xyz/api/image?type=coffee`

**Comment by Nsadow311** [comment]
Oh my god, I didn't even think of that, thank you Alva

**Comment by Allvaa** [comment]
no prob
